branches:
  only:
  - master  
  
matrix:
  include:

    # Backend tests
    - language: java

      before_install:
        - chmod +x ./gradlew
        - chmod +x ./resetdb.sh
      script:
        - ./resetdb.sh
        - ./gradlew build


    # Postman integration tests
    - language: node_js
      node_js:
          - "10.15"

      before_install:
        - chmod +x ./gradlew

      install:
          - npm install -g newman

      before_script:
          - node --version
          - npm --version
          - node_modules/.bin/newman --version
          - chmod +x ./resetdb.sh

      script:

          - ./resetdb.sh
            
          # run Spring app in background
          - ./gradlew bootRun &

          # give time for app to startup
          - sleep 60        

          # run test suites geenrated from Postman
          - node_modules/.bin/newman run ./OnlineGallery-Backend/src/test/java/ca/mcgill/ecse321/onlinegallery/controller/AdminAPI.json ./OnlineGallery-Backend/src/test/java/ca/mcgill/ecse321/onlinegallery/controller/ArtistAPI.json ./OnlineGallery-Backend/src/test/java/ca/mcgill/ecse321/onlinegallery/controller/ArtworkAPI.json ./OnlineGallery-Backend/src/test/java/ca/mcgill/ecse321/onlinegallery/controller/CustomerAPI.json ./OnlineGallery-Backend/src/test/java/ca/mcgill/ecse321/onlinegallery/controller/RegistrationAPI.json

